### ISSUE TITLE
Unable to allocate units

### ISSUE THREAD

**Issue by dp-0102** [DReichLab/EIG#103]
I'm trying to get a subset of populations from the AADR 1240k dataset, however when I run the convertf command, it aborts and shows an error message that says:

fatalx:
Unable to allocate 5052887274 unit(s) for item
Aborted

This memory allocation error appears regardless of how many populations I list in my poplist file. I've provided the information of my par file below

genotypename:    1240.geno
snpname:         1240.snp
indivname:       1240.ind
outputformat:    EIGENSTRAT
genotypeoutname: subset.geno
snpoutname:      subset.snp
indivoutname:	 subset.ind
poplistname:	 pops.txt

**Comment by MatthewMah** [comment]
The current software unfortunately allocates the complete matrix of genotype values in memory and loads the input file, so memory requirements depend on the input file and not just the desired output. We will likely have additional tools available in the next month or two to work around this memory requirement issue.
