### ISSUE TITLE
Dead link in EIGENSTRAT/README

### ISSUE THREAD

**Issue by andreasnoack** [DReichLab/EIG#11]
https://github.com/DReichLab/EIG/blob/master/EIGENSTRAT/README#L17 has a link to http://www.hsph.harvard.edu/faculty/alkes-price/files/eigensoftfaq.htm but the link returns 404.

Same link is here https://github.com/DReichLab/EIG/blob/master/POPGEN/README#L344

**Comment by kgalinsky** [comment]
Fixed the URLs in latest commits and in upcoming 6.1.4 release.

https://github.com/DReichLab/EIG/commit/e7e32c8871d752fc366934bf8e61c935ab1ed248
https://github.com/DReichLab/EIG/commit/e32d622ff72ef059b86c96146790481ab9662638
