### ISSUE TITLE
Trace Calculation in Output of smartpca

### ISSUE THREAD

**Issue by tamarcrum** [DReichLab/EIG#16]
I am working with SNPWEIGHTS (https://www.hsph.harvard.edu/alkes-price/software/ )  I need the trace that is calculated in smartpca.  

I have noticed that the line that prints "trace" to the output is commented out in src/eigensrc/smartpca.c on line 1138.  Would it be possible to compile a version where this print is done?

**Comment by bumblenick** [comment]
Can't you do this in your space?  smartpca already has too many options...

Nick
