### ISSUE TITLE
eigen values for stratified population

### ISSUE THREAD

**Issue by shirleydaidai** [DReichLab/EIG#20]
Hello,
Please forgive me if it's not the right place to ask this question. 
When I have a stratified study population, should I use Principal Componets (eigen values)  extracted from *.evec file with the whole population, or those PCs extracted from seperate population?
I'm really confused for a long time.
Thanks
Shirley

**Comment by bumblenick** [comment]
The normal thing to do is to compute eigenvectors using all your samples
and then use the eigenvectors as covariates.  EIGENSOFT has software
to make this easy (I hope),


Nick
