### ISSUE TITLE
Manual?

### ISSUE THREAD

**Issue by royfrancis** [DReichLab/EIG#22]
Where is the manual/user guide? What does this software do and how does one use it? All I can find is this github repo and this [link ](https://www.hsph.harvard.edu/alkes-price/software/).

**Comment by francescomontinaro** [comment]
Hi, the instructions are in README form:


See CONVERTF/README for documentation of programs for converting file formats.
See POPGEN/README for documentation of population structure programs.
See EIGENSTRAT/README for documentation of EIGENSTRAT programs.
