### ISSUE TITLE
ploteig is absent from repo

### ISSUE THREAD

**Issue by nadavrap** [DReichLab/EIG#25]
I realized in this version (7.2.1), that `ploteig` is absent.
smartpca.per still accept the `-p` option, but does not produce the plots.
Is it intentionally, or a misunderstanding?

**Comment by nadavrap** [comment]
`ploteig` was put back under [`bin` directory](https://github.com/DReichLab/EIG/tree/master/bin)

**Comment by MatthewMah** [comment]
Yes. Apologies for being terse and using the commit message only. We realized we accidentally removed `ploteig` and readded the latest version.

**Comment by nadavrap** [comment]
Great, now it is back again.
Thank you
