### ISSUE TITLE
lsqproject, how to set which samples to project and which samples to compute

### ISSUE THREAD

**Issue by silvewheat** [DReichLab/EIG#32]
Hello,
        I wonder when using lsqproject, how to set which samples to project and others to calculate?
        I checked the README but can't find the answer.

THANKS !
Yudong Cai

**Comment by bumblenick** [comment]
Typically you do this with poplistname.  List the populations to compute
axes for
1/line.

Nick

**Comment by silvewheat** [comment]
Get it!
Thank you very much!
