### ISSUE TITLE
readsnpmap data bad line

### ISSUE THREAD

**Issue by Zepeng-Mu** [DReichLab/EIG#34]
I am using `smartpca` binary. I used plink `bed`, `pedsnp` and `pedind` files. I got this error but have no idea what's going wrong:

> fatalx:
(readsnpmapdata) bad line: AAGATAATACCACACAGAGCACACAGCATCAGGAAAGGGTGAGCCACGTTTGAAGAACAGTGAGTGTTCTGGATGGCTGGCAGCTCAGACAGGTGGGCAGGAAAGAGTAGAGATGGCAAGAGACAGGTTAGCAAGGGCCTGGAGGACTGGGCTGGAGGTTGGACTTGAGGCTACTGAGTAGTGTCCAGTGCTGAGATATCAGTCACATTTTTGGAAAAGGGAAATGACTCAAAGTTAAGCCACCATTTATTGAGCTTATACGATATACTAGGCACCAGCCGAGCACATTGTATGCATTCCTCATTTATTTTATTTTTACTTTTATTATTACTTTTTGAGAAGGATTCTCACTCTGTCACCCAGGCTGGAGTGCAGTGGTGCAATCTCTGCTCACTGCAACCTCCGTCTCCTGGGTTCAAGCAATTCTCCTCCCTCAGCCTCCCGAGTAGCTGGAACTGCAGGTGCCCACCACCACACCTGCCTAATTTTTGTATTTTTAGTAGAGATGGGG
/tmp/slurmd/job58222214/slurm_script: line 11: 37882 Aborted                 smartpca -p smartpca.par

I have used `smartpca` with the same type of plink but from another dataset before. How can I slove this?

Many thanks

**Comment by bumblenick** [comment]
Try and use PLINK to make packed plink files
.bed .map etc. and then convertf to make Reich lab files

N

**Comment by Zepeng-Mu** [comment]
If I use `convertf`, the same error persists. I think there is something wrong with my `bed` file, but cannot think of why.

**Comment by Zepeng-Mu** [comment]
Hi, just as a follow-up, I think the problem here is that I did not know I have structural variations in my VCF files. Some of them are really long and are causing problems in the map file.
I think this issue might be closed.
Many thanks!

**Comment by bumblenick** [comment]
Thank you for letting me know.   It was always likely that there was
something
odd about your input, and I'm glad that you found it.

Nick

**Comment by SiddhiJani** [comment]
hi I am getting the same error
fatalx:
(readsnpmapdata) bad line: ACCATCACCACCACCAC

Aborted (core dumped)
what to do, I do have INDEL in my file but is there anyway to work on it without removing the INDELs

**Comment by bumblenick** [comment]
Indels are not supported ...

Nick

**Comment by SiddhiJani** [comment]
Okay, Thank you
