### ISSUE TITLE
**warning: dubious parameter, please check the parameter name evecoutname

### ISSUE THREAD

**Issue by 2007lab** [DReichLab/EIG#40]
smartpca does everything but output the evec.
Any idea why this is a problem?
parameter file: 28K_EigenStrat3.pca.par
**warning: dubious parameter, please check the parameter name evecoutname:ForEIGENtest4evec.out
### THE INPUT PARAMETERS
##PARAMETER NAME: VALUE
genotypename: ForEIGENtest4.bed
snpname: ForEIGENtest4.bim
indivname: ForEIGENtest4.fam
evecoutname:ForEIGENtest4evec.out
evaloutname: ForEIGENtest4.eval
altnormstyle: NO
numoutevec: 4
numoutlieriter: 5
numoutlierevec: 10
outliersigmathresh: 6.0
qtmode: NO
outlieroutname: ForEIGENtest4.TXT
normalexhet: YES
outputformat: PACKEDPED
## smartpca version: 16000
norm used

**Comment by bumblenick** [comment]
You need a space after evecoutname:

Nick

**Comment by 2007lab** [comment]
Thanks !
