### ISSUE TITLE
convert genotypes  of the binary form 

### ISSUE THREAD

**Issue by xiaoqiwang19** [DReichLab/EIG#48]
Hi  all:   
   I downloaded the 1240K dataset. The file of genotypes are in a binary form , and when I want to convert the binary form to eigenstrat  form  by convertf  software, my command line is as follows:
bin/convertf  -p  par.ANCESTRYMAP.EIGENSTRAT 

par.ANCESTRYMAP.EIGENSTRAT:
genotypename:    v42.4.1240K.geno
snpname:         v42.4.1240K.snp
indivname:       v42.4.1240K.ind
outputformat:    EIGENSTRAT
genotypeoutname: 1240K.eigenstratgeno
snpoutname:      1240K.snp
indivoutname:    1240K.ind

I found that the results were all numbers. I don't know Whether  I'm using the tool in the wrong way.
We are looking forward to your help and your reply.

**Comment by bumblenick** [comment]
When you say the "results are all numbers" which output files?   All 3?
That's strange!
eigenstrat format will produce a large geno file on the 1240K data.

Nick

**Comment by xiaoqiwang19** [comment]
The results of all numbers as follows:
0999992099992999999992909929999999999990992009029900020092990090999009200000009999990000220990099000090099990209200900222909900000909290990000000099999090200900900920990209999992999009001120020100929911020211101100021019100900121900100011000090010910010020110000000009090000010000100120100009000001001201100111001011000000000000100900001100111010111000911129001199020100110010101109000200000009001119020210000010011000000011000001902000000101000219090100099100900110000999999011010010120020022000000099999999999999909999999999000009990900009000999999999900029090029090299999900009200099999999909099090909990990999929999992000099999099999990299090999999999002000099990299920900900099999299999999999099999999090909999999999909009909922909999999909290990000909009200099209099099099009999999909029209999900990009900000000000090902220000209290000009000020009099999920920090909999000000909290000999090099990009999999909999999999999999999990099099999999999099999990000020290000099999222099999999099999999200909990990090099022002000000090009009999092990999900990009999990999099900209999099999990900000999290099999900000090990009000090009990009920000909902900099002000000999920090999990009999909902099990990999099909299999999099009009209020002200009009000999099999990909999299990090929090000290999022009029009099990999900999990990200090900090090200000900999009999990909999999099990099002200909999990990990009990902290902209000090920999900009900990000009999990900099999999990099999999090990020000090090000000090009299092099909009000999992209002292000000000000000000000000000200000000000000009200000000090000200200020000002020202000000000000000000000000000222002200000002000020000220000000000000000002000022200000000000200020000002000000002000000002002000000002200000000020200000000020200020200000002000000200000002000000000000020000000000000000200000000000000000000002000000000000000000000000022000000002002000020002200000020000000000002200020000000000000000000000000000000000000000002202000000000000002022000000000020200000000002000000020000000000002200000000200000002000000000220000200000002000000020000000000200000000000200200000000000000002000000002000000000200000000000000000000000000002200000000020000000000000002000022222022002022000200020000220000002200022000002022002022002200000002222000022000000000000202022000200000000000002020002002200200002000000000002200000020000000000000000000000000020002002020200000000220202000000020020220220200020000000000020000000000000000000000200020000202222202002200200022200220220000200000000220020222000222022200020000020222202202020000000000000000002020000000000000000200202022002202220000000000202000020220200220000202200022202220200020022200002020222222200000000000002202020000222202020020220002000220222200002200220002222222200222000222222222200202000020022202222000000222220222022220022220222202022202022022222220220200000200222200022022222220022222000202220000020002200000000020000002020000000200022000000002000000000000000000022200200020200000000200002022000200200000000000000200000200000002200000000000000000000000022000020002020000000000000000200202020000000000002202000000002200020200002000200022000020000000002002020000200200000000000200200000000000000002000000200002000000022002202000002000000000000000000000000200000000020000000000000000000000000200000202200002200022020020020202000000000200002200000000000000000020000000000000000000000000000200000000000000002000000020000000000000090222220000022202222020002220000000000000000000002000000200000000000000000020000200000000000000202022020220022020220200000000000900000000209020000000002922020202292222222200922000222202020220222222202220920002020200292200020022002222200020200220222222202202022222000009090002002200020002022200002002220002002000000000000290222000002000000000200000002000000000000000000022020002200202220020220000222222920090020200020020022220222000000000000022000000200000000020000000000020000000000020000000200000000202000222000000209000000200000000020200000200000000000002000000020020002000000020000000000000020002000020020200002022000020000000020200000000299999909999999999929909909099090090999999000999909929000099900990090209209000000090009009999099000002009000209000002209900090099000000900900000009090990909090999909999999099999990099999999999999999999002000000000200000022000000020000000000000000000000000000000000022002090029002099090902920009990299900999999900022000909000009990909099900909099999999099909909909999090000999900909999999999999099099009900020209099999999999990999999999990090290999920090999990099209900999000909999900000900099999029000090999992299990990099992090990999990090902900999002999999992200999999999999909202000099220999029999999990999009099900200002090002099990090990999002009999909999099999909009909009000092902090090000999092099099009090999090909990999990000909990900000200000299909209999999990090000990999299299992999999909099990020900902099909292029999999299999999922929200229002009099999999999990990999999999909999999999000022000002999999999999999999999000209099999900999909009099999999999999999200990922209929222200992999999999099099029909009009909990900099000902990999990099099990900299920999009099999999000900999992929999999990999900209900099292000999099990999900999909999900909999999909990999099009999000000000000200009920999299099999999990299090090002000000000020202909099099909000999209090290900000202000000000001999990990990099990099999999999992992999999999909999990099999009009999090999299999099990099290999900902099999999999099999992999299909999209999999999999990999099999999909909002209090909900092990999999099999999000990099999009999000029909099290009009900999999090999099999990200909900999900090092900009909909029099999999999099999900922299909009009209002022909929090999990099090000999299002020020099000090990999999099999999992929900990000299209009092090999999009990009209000009002000000299900029090009209900999099999999909009099999909999990090909999909099999992009009990002009909290999909009090209090090099922000900999999999999909999999999999999999999999299999999299999920000900009000009000090000000909090999999990999909090099099909009920999099990999999099990200999999999909999990900999099099990009909990099900090090909092099999020000909009990999290999990999009929990990999990999990999099999999999999999909999999999999999099999920992999999900999999999999909999099990999999999999999999999999999999999999999999999999999999920909999999999929909999999929999990090009009099090909000990290900099020000002002092990909999920920909900000299920009000000000000900020000000920009002000900929290999990999000099002200999999900009999200200099909020290090920000000900099999990909029929099099090900999999990999990922999009990920999

I don't know Whether I'm using the tool in the wrong way.
I am confused.

**Comment by bumblenick** [comment]
This looks like a standard eigenstrat formatted file
If there is a problem you need to be specific

N

**Comment by xiaoqiwang19** [comment]
OK. Thank you!
