### ISSUE TITLE
The columns name and output for fstdetails

### ISSUE THREAD

**Issue by lw157** [DReichLab/EIG#50]
Hi,
   I got the Fst for individual SNPs, but I can not find the explanation of  "N", "D", and "Ratio". What do they mean? Could you provide any reference? 

_## pop 1          pop 2            snpname                    N                    D        Ratio 
 Pop1                 Pop2          rs367896724    -0.016066     0.498047    -0.032258
 Pop1                 Pop3         rs367896724    -0.011908     0.494141    -0.024098_

Thanks a lot.
Liuyang

**Comment by kristjanmoore** [comment]
Hi Liuyang, 

I'm not affiliated with Nick Patterson or the Reich or Price labs in any way (I just use EIGENSOFT a lot!), so take what I say with a pinch of salt, but I believe that:

* EIGENSOFT implements the Hudson estimator for Fst calculations (see "Recommendations" and Equation 10 in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3759727/ )
* "N" stands for numerator [of the Hudson estimator]
* "D" stands for denominator
* "Ratio" is N/D, which is the Hudson estimator of Fst

**Comment by bumblenick** [comment]
Fst is calculated as N/D
N = ave((p1-p2)^2)
D = ave(p1(1-p2)+(p2(1-p1))

Nick

**Comment by lw157** [comment]
Thank Kris and Nick. This is very helpful.
I will close this issue.
Liuyang

**Comment by kristjanmoore** [comment]
So if Equation 10 from the paper I linked is indeed EIGENSOFT's implemented formula for the (per-variant) Hudson estimator for Fst, I think it's easy for the two minus terms to pull the numerator below 0 when the sample sizes are small, or when the p1 and p2 values are very close and therefore don't show much evidence of differentiation.

(Also, I believe the formula Nick provided is for the "ratio of averages" *genomewide* Fst, hence the ave() on the numerator and denominator.)

**Comment by lw157** [comment]
> So if Equation 10 from the paper I linked is indeed EIGENSOFT's implemented formula for the (per-variant) Hudson estimator for Fst, I think it's easy for the two minus terms to pull the numerator below 0 when the sample sizes are small, or when the p1 and p2 values are very close and therefore don't show much evidence of differentiation.
> 
> (Also, I believe the formula Nick provided is for the "ratio of averages" _genomewide_ Fst, hence the ave() on the numerator and denominator.)

Yes, this makes sense. In Eq 10, it does generate negative values when n1 and n2 are very different.
Thank Kris again.

Liuyang
