### ISSUE TITLE
smartpca: error : snpnameAborted

### ISSUE THREAD

**Issue by CarBarJon** [DReichLab/EIG#52]
HI! 
I'm trying to run smartpca but I'm having this error 

`fatalx:
(getsnps) null snpnameAborted (core dumped)`

Not sure how to fix it 
Any idea? 
Thanks!

**Comment by bumblenick** [comment]
Show me your parameter file but I betcha you have no snpname: entry

N

**Comment by CarBarJon** [comment]
genotypeoutname: aDNA_OGVP_1_23.geno
snpoutname: aDNA_OGVP_1_23.snp
indivoutname: aDNA_OGVP_1_23.ind
evecoutname: aDNA_OGVP_NoMada.evec
evaloutname: aDNA_OGVP_NoMada.eval
poplistname: PopPCA.txt
lsqproject: YES
numoutevec: 4
numthreads: 10

**Comment by CarBarJon** [comment]
genotypeoutname: aDNA.geno
snpoutname: aDNA.snp
indivoutname: aDNA.ind
evecoutname: aDNA.evec
evaloutname: aDNA.eval
poplistname: PopPCA.txt
lsqproject: YES
numoutevec: 4
numthreads: 10

**Comment by CarBarJon** [comment]
I realize the problem! its that I'm using the out in the par files!

**Comment by CarBarJon** [comment]
@bumblenick  Thanks for responding! Have a nice day!

**Comment by beibeixiaomu** [comment]
@CarBarJon 
Hello！I met the same problem. But I do not know the meaning of "I'm using the out in the par files". Could you explain it to me, please? Thank you very much.

**Comment by bumblenick** [comment]
Car had snpoutname:
should have been snpname:

N
