### ISSUE TITLE
fatalx: OOPS snp file has changed since genotype file was created Aborted (core dumped)

### ISSUE THREAD

**Issue by MaryBioinfo** [DReichLab/EIG#59]
Hello,
I tried to run smartpca for par file and input files ( .geno, .ind, .snp). They are in the same directory. My sample includes both ancient and present, So I used option: isqproject: YES. SNP file contains 597,573 sites, IND file includes 11,152 individuals. And I use the LINUX command to get the modernpoplist.txt : cat xx.ind | awk '{print $3}' | grep -v -E "N|BA|CA|IA" | sort | uniq -c > modernpoplist.txt. And I run: smartpca -p Par. However, I get error saying:
fatalx:
OOPS snp file has changed since genotype file was created
Aborted (core dumped)

My Par file looks like:
genotypename: xx.geno
snpname: xx.snp
indivname: xx.ind
evecoutname: xx.evec
evaloutname: xx.eval
poplistname: modernpoplist.txt 
lsqproject: YES 
numoutevec: 4
fastmode: YES 

Thank you for your attention to this matter. I would appreciate your help.

**Comment by bumblenick** [comment]
The error message is clear.  Either you edited the .snp file or the .snp
file is
misformatted.  You didn't say how the .geno and .snp files were made and
this
is what matters here.

Nick
