### ISSUE TITLE
No 'convertf file' in bin

### ISSUE THREAD

**Issue by Skylette14** [DReichLab/EIG#60]
Dear all

I am trying to use the convertf program, in the README file, line 148, said that 'The syntax of convertf is "../bin/convertf -p parfile".'.  But I can not find convertf under bin or other folders. 

Thank you for your attention to this matter. I would appreciate your help.

**Comment by kristjanmoore** [comment]
I'd guess that you haven't run `make` yet. As the README says:

> We have placed source code for all C executables in the src/ directory, for users who wish to modify and recompile our programs.
> `cd src`
> `make`
> `make install`

**Comment by bumblenick** [comment]
Matt: Please answer this lady.

**Comment by MatthewMah** [comment]
I think @kristjanmoore is correct. The convertf binary is built and placed in the bin directory by running `make` and `make install` from the `src` directory.
