### ISSUE TITLE
smartpca decimal places

### ISSUE THREAD

**Issue by brautaz** [DReichLab/EIG#63]
Hi nick,
how do I specify the n of decimal places I want outputted in my final .evec file? The default is 4, I'd like to have 6 decimals for my pca coordinates. Thx in advance!

**Comment by bumblenick** [comment]
hiprecision: YES
in parameter file

Nick

**Comment by brautaz** [comment]
I put this in the parameter file and my .evec values are still in 4 decimals

**Comment by bumblenick** [comment]
check your spelling of parameter
hiprec: YES
will also work
Make sure you are using the latest version

**Comment by brautaz** [comment]
> ### THE INPUT PARAMETERS
> ##PARAMETER NAME: VALUE
> genotypename: /Users/brautaz/Desktop/1000G/phter/ph2ter.geno
> snpname: /Users/brautaz/Desktop/1000G/phter/ph2ter.snp
> indivname: /Users/brautaz/Desktop/1000G/phter/ph2ter.ind
> evecoutname: /Users/brautaz/Desktop/1000G/phter/ph2ter.evec
> evaloutname: /Users/brautaz/Desktop/1000G/phter/ph2ter.eval
> lsqproject: YES
> numoutevec: 25
> numthreads: 1
> hiprecision: YES
> ## smartpca version: 16000
> norm used
> 
> lsqproject used
> number of samples used: 1375 number of snps used: 80348

Using the newest code: 

>                 name     PC1     PC2     PC3  ...    PC23    PC24    PC25         population
> 0       FAM001:ID001 -0.0070 -0.0086  0.0043  ... -0.0018 -0.0133  0.0164             ph2ter
> 1         116:ARK-59  0.0425  0.0650  0.0220  ... -0.0039  0.0024  0.0200  Armenian_Hemsheni
> 2         117:ARK-72  0.0047  0.0393  0.0017  ...  0.0032  0.0013 -0.0018  Armenian_Hemsheni

**Comment by brautaz** [comment]
Maybe there is a hard-coded solution to this?

**Comment by bumblenick** [comment]
We are about to put a new release of smartpca on github.  I specifically
tested
hiprecision: YES  on the new release.
So wait a couple of days. and try again.

Nick

**Comment by bumblenick** [comment]
New version of smartpca (version 18140) now on github,
For more precision (6 decimal places on evec output, code
hiprecision:  YES
or
hiprec:   YES

**Comment by brautaz** [comment]
This worked! TY

**Comment by bumblenick** [comment]
Great;  I don't know why it  didn't work before but
I am not going to worry about it.

Nick
