### ISSUE TITLE
Error in "make"  without any reminder.

### ISSUE THREAD

**Issue by JFF1594032292** [DReichLab/EIG#69]
Hi,
I tried to install EIG according to the readme:

> "cd src"
> make LDFLAGS="-L/home/jiangfeng/anaconda3/lib -L/usr/lib -L/usr/lib64 -L/usr/local/lib -L/usr/local/lib64" CFLAGS="-I/home/jiangfeng/anaconda3/inlude -I/usr/local/include -I/usr/include"   

And it reported an error when "make": 

> /home/jiangfeng/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -L/home/jiangfeng/anaconda3/lib -L/usr/lib -L/usr/lib64 -L/usr/local/lib -L/usr/local/lib64  baseprog.o mcio.o egsubs.o admutils.o h2d.o eigensrc/exclude.o nicksrc/libnick.a  -lgsl -lopenblas -lm -lpthread -o baseprog
> collect2: error: ld returned 1 exit status
> make: *** [<builtin>: baseprog] Error 1

I checked the library and there is no lack of  -lgsl -lopenblas -lm -lpthread or liblapack. The error also doesn't remind which library was lacked. 
I don't know how to solve it, can you give me some advice?

Thanks!
Jiang

**Comment by MatthewMah** [comment]
This StackOverflow answer suggests adding `-Wl,-V` to LDFLAGS to get more information. 
https://stackoverflow.com/a/32711542/4107809

**Comment by JFF1594032292** [comment]
It worked! Thanks!
