### ISSUE TITLE
lapacke_mangling.h missing

### ISSUE THREAD

**Issue by rekado** [DReichLab/EIG#7]
Building of the latest version from git fails with the following error:

~~~
gcc -L/opt/openblas/lib -D_GNU_SOURCE  eigensrc/twstats.o nicksrc/libnick.a  -Wl,-Bdynamic -lgsl -Wl,-Bstatic -lopenblas -Wl,-Bdynamic -lgfortran -pthread -lm -llapack -o eigensrc/twstats
In file included from ksrc/kjg_gsl.c:10:0:
../include/lapacke.h:143:30: fatal error: lapacke_mangling.h: No such file or directory
 #include "lapacke_mangling.h"
                              ^
compilation terminated.
<builtin>: recipe for target 'ksrc/kjg_gsl.o' failed
make: *** [ksrc/kjg_gsl.o] Error 1
make: *** Waiting for unfinished jobs....
~~~

Should the repository contain a file called "lapacke_mangling.h"?

**Comment by rekado** [comment]
Do you have any suggestion how to avoid this?  Or instructions on how to get that file?  I cannot seem to build this package because of this error.

**Comment by kgalinsky** [comment]
lapacke_mangling.h is included in newer LAPACK distributions that contain lapacke. This isn't something that we should be including in this repository.

**Comment by rekado** [comment]
Thank you, I see that our "lapack" package didn't enable the build of "lapacke" (it is disabled by default).  I assumed "lapacke_mangling.h" was a repository-local file, because it is in double quotes.
