### ISSUE TITLE
genotype file bad line

### ISSUE THREAD

**Issue by DcornishUCL** [DReichLab/EIG#73]
Hi, 

I have been trying to perform mergeit and I am receiving the error below:

fatalx:
file.geno bad line: 92992229999999999929992999992229992299999929299992

I checked whether the number of characters in each line == number of individuals and indeed lines have the expected 50 individuals suggesting the error is not caused by missing individuals. I did the same with the number of SNPs and all is as expected. Any help you could offer to help me rectify this problem would be much appreciated. I attach a few lines of the  offending .geno file below in case this helps. 

Best, 

Dean

geno.file:

92992229999999999929992999992229992299999929299992
92992229999999999929992999992229992299999929299992
90999229999999999929992999992229992299999929299992
22299229999929999222999992929929999999999229922992
29299229999999999929999999922229929929999929292999
22222229999929929929992992922229929929999229222929
22222229999929929929992992922229929929999229222922
22222229999222929929992992922229929929999229222922
22222229999222929929992992922229929929999229222922

**Comment by bumblenick** [comment]
1. Please check that your param file doesn't have some error (like
specifying an ind file as a geno file
2. Check that the geno file doesn't have strange characters like tabs.

This is some input blunder with probability .999999
For further correspondence please email me direct:  <
***@***.***>

Nick

**Comment by DcornishUCL** [comment]
Hi, 

Yes, I spotted it! I had mistakenly specified the ind as the geno file. My apologies, thank you for alerting me to this.
