### ISSUE TITLE
Error during make in Ubuntu

### ISSUE THREAD

**Issue by curiosusJR** [DReichLab/EIG#77]
Hi,
I have downloaded the EIG v7.2.1 and installed the packages depends manually followed by readme. But there is a error message when I try to execute "make &&  make install". 

Here is the error message:
```
cc   baseprog.o mcio.o egsubs.o admutils.o h2d.o eigensrc/exclude.o nicksrc/libnick.a  -lgsl -lopenblas -lm -lpthread -o baseprog
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lgsl
collect2: error: ld returned 1 exit status
make: *** [<builtin>: baseprog] Error 1
```

Then, I have tried this:

> make CFLAGS="-I/n/app/openblas/0.2.19/include -I/n/app/gsl/2.3/include" LDFLAGS="-L/n/app/openblas/0.2.19/lib -L/n/app/gsl/2.3/lib/"

and this:

> make CFLAGS="-I/usr/local/OpenBLAS/include  -I/home/junru/GSL-4.0.0/include " LDFLAGS="-L/usr/local/OpenBLAS/lib -L/home/junru/GSL-4.0.0/build-x86/lib  "

But the error still occurred. Please help me, what should I do. 

Thank you very much.

**Comment by MatthewMah** [comment]
This error message says the linker cannot find the gsl library. You have to make sure the library is built and point the linker to it.
