### ISSUE TITLE
all samples being ignored by convertf

### ISSUE THREAD

**Issue by hhg7** [DReichLab/EIG#78]
I'm running EIG 7.2.1 and using convertf to make a geno file with the following parameters:

```
genotypename:	merged.eigenstrat.34string.length.beded
snpname:	merged.eigenstrat.34string.length.map
indivname:	56001801066929_WGZ.snp.fam
outputformat:	PACKEDANCESTRYMAP
genotypeoutname:	merged.eigenstrat.34string.length.geno
snpoutname:	merged.eigenstrat.34string.length.snp
indivoutname:	merged.eigenstrat.34string.length.ind
familynames:	NO
```
This is only being done for chr22 as a tutorial for myself to generate an easy-to-use wrapper.

I have about 2,504 1000Genomes samples, with one additional unknown sample added in.

The original input is a VCF, which has been modified so that the `ID` column has only strings < 35 characters long.

the bed file was generated thus:

`~/Scripts/plink1.9/plink --vcf merged.eigenstrat.34string.length.vcf --make-bed --out merged.eigenstrat.34string.length`

and the map file thus:

`~/Scripts/plink1.9/plink --vcf merged.eigenstrat.34string.length.vcf --recode --out merged.eigenstrat.34string.length`

The end of the fam file looks like:

```
Y035	NA19198	0	0	1	-9
Y010	NA18511	0	0	2	-9
Y035	NA19197	0	0	2	-9
Y014	NA18519	0	0	1	-9
56001801066929_WGZ	56001801066929_WGZ	0	0	0	-9
```
The added sample is the last line.
when I run convertf: `bin/convertf -p convertf.params.txt`

I get a repeat of the input parameters and then the following to STDOUT:

```
genetic distance set from physical distance
HG01889 ignored
HG01894 ignored
HG01958 ignored
HG02314 ignored
HG01989 ignored
...
NA18511 ignored
NA19197 ignored
NA18519 ignored
56001801066929_WGZ ignored
all individuals set ignore.  Likely input problem (col 6)
resetting all individual...
genotype file processed
numvalidind:   2505  maxmiss: 2505001
packedancestrymap output
##end of convertf run
```

Why are all individuals being ignored?

How can I modify the input to get rid of the `input problem`?
How can I modify the file so that all individuals are converted?

**Comment by bumblenick** [comment]
I'm not an expert on PED  format but I think you may have marked all your
 samples to be ignored.  By your output suggests that convertf rescued you,
Does the .ind file look OK maybe with pop labels ???

And run with just a few samples and outputformat: eigenstrat
to see if you are getting data.

**Comment by hhg7** [comment]
Hi @bumblenick 

the ind file looks like

             HG02449 U        ???
             HG02554 U        ???
             HG02332 U        ???
             HG02577 U        ???
             HG01885 U        ???
             HG02537 U        ???
             ...

I'm guessing that the `???` shouldn't be there.

the example shows that the ind file should look like:

more EIGENSTRAT/example.ind

             SAMPLE0 F       Case
             SAMPLE1 M       Case
             SAMPLE2 F    Control
             SAMPLE3 M    Control
             SAMPLE4 F    Control

so perhaps I could put

             HG02449 M        CEU
             HG02554 F        YRI
             HG02332 M        GWD
             HG02577 F        FIN
             HG01885 M        GBR
             HG02537 F        TSI

the sexes and ethnicities aren't correct, but I'll give a try to the real thing and let you know

But what about the geno file? what that be wrong too?

**Comment by bumblenick** [comment]
No the ??? is OK -- you haven't specified pop labels.
For your application you need to modify the .ind file with the labels you
want.
But I think you likely have real genotype data output here.

This is probably about as much help as I can give

N

**Comment by hhg7** [comment]
the problem was in the fam file.  The fam must end in `1` for all samples.  I had `-9`
