### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64: issue

### ISSUE THREAD

**Issue by hyunnnie** [DReichLab/EIG#85]
Dear everyone, 

I tried running the 'make' code, but when running make I only get the error: 

`ld: symbol(s) not found for architecture x86_64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make: *** [eigensrc/smartpca] Error 1`

I guess it doesn't work yet on macOS with Apple Silicon (M1) Chip?
Any recommendation how to bypass that?

Kind regards, 
hyunnnie

**Comment by MatthewMah** [comment]
Can you build hello world with this environment?

**Comment by hyunnnie** [comment]
No, I cannot build that environment. 
So I download 'Rosetta 2' and change the environment into x86_64. And it works! :)
