### ISSUE TITLE
There is no "convertf" in the bin folder.

### ISSUE THREAD

**Issue by ZhenyaoYe** [DReichLab/EIG#89]
Hi, 

I downloaded the zip file of this EIG. But I did not see convertf stored in bin folder. Anyone can help me this matter? Thank you! 

Best regards,
Zhenyao

**Comment by bumblenick** [comment]
The executables should be recompiled

make convertf

Nick

**Comment by ZhenyaoYe** [comment]
Thank you so much for your response, Nick! It works now. 

Zhenyao

**Comment by Phiphigenes** [comment]
Hello

I work on Mac and when I enter : make convertf I got an error message :

ld: library not found for -lgsl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [convertf] Error 1

What could I do to solve this issue ?
Thank you

Philippe

**Comment by Phiphigenes** [comment]
Hello
I have solve the issue by installing Homebrew then gsl and openBlas.
Now it works fine!
Philippe
