### ISSUE TITLE
Output Files Not Being Made

### ISSUE THREAD

**Issue by dogcow4958** [DReichLab/EIG#98]
Hello,

In all sub-programs of EIGENSOFT, when I run a command, the command line states that the run is successful (I receive the "____ output" message and "end of ___ run" message). However, no output files are made in the directory.

I have tried running programs such as smartpca and convertf on files that would previously result in the creation of successful output files, and no output file is made as of now.

Is there any way to rectify this?

Thank you very much.

**Comment by MatthewMah** [comment]
Please check your parameter files for where you are instructing output to be written.

**Comment by dogcow4958** [comment]
Thank you!
