### ISSUE TITLE
Can smartpca output fst value for each SNP?

### ISSUE THREAD

**Issue by minglibio** [DReichLab/EIG#99]
Hi,

When I run smartpca to estimate the Hudson's fst, I only get a whole genome pair-wise fst. I am curious if I can get the fst value of each SNP using smartpca, if so, which parameter should I add?

The output I got is like this:
```
## Fst statistics between populations:     fst     fstjack       std error      Z    snpnumber
F_st                    pop1                    pop2    -0.004134750    -0.004133115     0.001098870    -3.761 241609
```

Best,
Ming

**Comment by bumblenick** [comment]
fstdetailsname:  <yourfile> 
fstsnpout:      YES

**Comment by bumblenick** [comment]
fstdetailsname:  <yourfile> 
fstsnpout:  YES
